# Generated by Django 3.1.7 on 2021-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210425_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(default='SOME STRING', help_text='Please put down your comments'),
        ),
    ]
